[package]
name = "repro"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
blake3 = "1"

[[example]]
name = "hash_record"
path = "examples/hash_record.rs"
