[package]
name = "repro_harness"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
repro = { path = "../../crates/repro" }
